const fs = require('fs');
const path = require('path');
const file = path.join(__dirname, 'index.tsx');

let content = fs.readFileSync(file, 'utf8');
const insertions = `
  "Vacancies": { fr: "Offres d'emploi", pt: "Vagas", ar: "الوظائف الشاغرة", sw: "Nafasi za Kazi", ha: "Gurbin Aiki", es: "Vacantes" },
  "Looking for Your Next Opportunity?": { fr: "À la recherche de votre prochaine opportunité ?", pt: "Procurando sua próxima oportunidade?", ar: "هل تبحث عن فرصتك القادمة؟", sw: "Unatafuta Fursa Yako Inayofuata?", ha: "Kuna neman damar aiki na gaba?", es: "¿Buscando tu próxima oportunidad?" },
  "Submit your CV today and we'll connect you with employers seeking qualified talent.": { fr: "Soumettez votre CV aujourd'hui et nous vous mettrons en contact avec des employeurs.", pt: "Envie seu currículo hoje e nós o conectaremos com empregadores.", ar: "أرسل سيرتك الذاتية اليوم وسنقوم بتوصيلك بأصحاب العمل الذين يبحثون عن المواهب المؤهلة.", sw: "Tuma CV yako leo na tutakuunganisha na waajiri.", ha: "Sanya CV dinka yau don mu haɗa ka da masu daukan aiki.", es: "Envía tu CV hoy y te conectaremos con empleadores." },
  "General Vacancies": { fr: "Offres Générales", pt: "Vagas Gerais", ar: "وظائف عامة", sw: "Nafasi za Kazi za Kawaida", ha: "Gurbin Aiki na Gaba ɗaya", es: "Vacantes Generales" },
  "Looking for employment? Submit your CV to be considered for current and future opportunities across various roles in our organization and partner network.": { fr: "Vous cherchez un emploi ? Soumettez votre CV pour être considéré.", pt: "Procurando emprego? Envie seu currículo para ser considerado.", ar: "هل تبحث عن عمل؟ أرسل سيرتك الذاتية ليتم أخذك بعين الاعتبار للفرص الحالية والمستقبلية عبر مختلف الأدوار في مؤسستنا وشبكة شركائنا.", sw: "Unatafuta ajira? Tuma CV yako.", ha: "Kuna neman aiki? Sanya CV ɗin ku.", es: "¿Buscas empleo? Envía tu CV para ser considerado." },
  "Submit Your CV": { fr: "Soumettre Votre CV", pt: "Enviar Seu Currículo", ar: "إرسال السيرة الذاتية", sw: "Tuma CV Yako", ha: "Sanya CV ɗin ku", es: "Enviar tu CV" },
  "Driver Vacancies": { fr: "Offres pour Chauffeurs", pt: "Vagas para Motoristas", ar: "وظائف السائقين", sw: "Nafasi za Kazi za Madereva", ha: "Gurbin Aikin Direbobi", es: "Vacantes para Conductores" },
  "Are you a professional driver looking for your next job? Submit your CV today and we'll connect you with employers seeking qualified drivers.": { fr: "Êtes-vous un chauffeur professionnel ? Soumettez votre CV aujourd'hui.", pt: "Você é um motorista profissional? Envie seu currículo hoje.", ar: "هل أنت سائق محترف تبحث عن وظيفتك القادمة؟ أرسل سيرتك الذاتية اليوم وسنقوم بتوصيلك بأصحاب العمل الذين يبحثون عن سائقين مؤهلين.", sw: "Je, wewe ni dereva mtaalamu? Tuma CV yako leo.", ha: "Kai ƙwararren direba ne? Sanya CV ɗin ku a yau.", es: "¿Eres un conductor profesional? Envía tu CV hoy." },
  "How Can We Help You?": { fr: "Comment pouvons-nous vous aider ?", pt: "Como podemos ajudá-lo?", ar: "كيف يمكننا مساعدتك؟", sw: "Tunawezaje kukusaidia?", ha: "Ta yaya zamu taimaka muku?", es: "¿Cómo podemos ayudarte?" },
  "Choose the option that best describes you.": { fr: "Choisissez l'option qui vous décrit le mieux.", pt: "Escolha a opção que melhor descreve você.", ar: "اختر الخيار الذي يصفك بشكل أفضل.", sw: "Chagua chaguo linalokufafanua vyema.", ha: "Zaɓi zaɓi wanda ya fi dacewa da kai.", es: "Elige la opción que mejor te describa." },
  "Looking for Employment?": { fr: "À la recherche d'un emploi ?", pt: "Procurando Emprego?", ar: "هل تبحث عن عمل؟", sw: "Unatafuta Ajira?", ha: "Kuna neman Aiki?", es: "¿Buscas Empleo?" },
  "Send us your CV and we'll consider you for current and future opportunities.": { fr: "Envoyez-nous votre CV et nous vous considérerons pour les opportunités.", pt: "Envie-nos seu currículo e o consideraremos para oportunidades.", ar: "أرسل لنا سيرتك الذاتية وسنأخذك بعين الاعتبار للفرص الحالية والمستقبلية.", sw: "Tutumie CV yako na tutakufikiria kwa fursa.", ha: "Aiko mana da CV dinka kuma za mu duba ka don damar aiki.", es: "Envíanos tu CV y te consideraremos para oportunidades." },
  "Driver Seeking Employment?": { fr: "Chauffeur cherchant un emploi ?", pt: "Motorista Procurando Emprego?", ar: "سائق يبحث عن عمل؟", sw: "Dereva Anayetafuta Ajira?", ha: "Direba na Neman Aiki?", es: "¿Conductor Buscando Empleo?" },
  "Send us your CV and we help connect you with transport companies looking for qualified drivers.": { fr: "Envoyez-nous votre CV et nous vous mettons en contact avec des entreprises de transport.", pt: "Envie-nos seu currículo e nós o conectaremos com empresas de transporte.", ar: "أرسل لنا سيرتك الذاتية وسنساعدك في التواصل مع شركات النقل التي تبحث عن سائقين مؤهلين.", sw: "Tutumie CV yako na tunakusaidia kukuunganisha na kampuni za usafiri.", ha: "Aiko mana da CV dinka kuma za mu taimaka wajen haɗa ka da kamfanonin sufuri.", es: "Envíanos tu CV y te ayudamos a conectar con empresas de transporte." },
  "Need Drivers?": { fr: "Besoin de Chauffeurs ?", pt: "Precisa de Motoristas?", ar: "هل تحتاج إلى سائقين؟", sw: "Unahitaji Madereva?", ha: "Kuna buƙatar Direbobi?", es: "¿Necesitas Conductores?" },
  "Transport Company Looking for Drivers? Send us your requirements, and we'll help connect you with suitable driver candidates.": { fr: "Entreprise de transport cherchant des chauffeurs ? Envoyez-nous vos exigences.", pt: "Empresa de Transporte Procurando Motoristas? Envie-nos seus requisitos.", ar: "شركة نقل تبحث عن سائقين؟ أرسل لنا متطلباتك، وسنساعدك في العثور على مرشحين مناسبين.", sw: "Kampuni ya Usafiri Inatafuta Madereva? Tutumie mahitaji yako.", ha: "Kamfanin Sufuri na Neman Direbobi? Aiko mana da buƙatunku.", es: "¿Empresa de Transporte Buscando Conductores? Envíanos tus requisitos." },
  "Email Us Your Requirements": { fr: "Envoyez-nous vos exigences par e-mail", pt: "Envie-nos seus requisitos por e-mail", ar: "أرسل لنا متطلباتك عبر البريد الإلكتروني", sw: "Tutumie Mahitaji Yako kwa Barua Pepe", ha: "Aiko Mana Da Buƙatunku Ta Imel", es: "Envíanos tus requisitos por correo electrónico" },
  "Send Email to:": { fr: "Envoyer un e-mail à :", pt: "Enviar e-mail para:", ar: "إرسال بريد إلكتروني إلى:", sw: "Tuma Barua Pepe kwa:", ha: "Aika Imel zuwa:", es: "Enviar correo electrónico a:" },
  "Terms of Use and Conditions": { fr: "Conditions d'utilisation", pt: "Termos de Uso e Condições", ar: "شروط الاستخدام والأحكام", sw: "Masharti na Vigezo vya Matumizi", ha: "Sharuɗɗa da Ka'idojin Amfani", es: "Términos de Uso y Condiciones" },
  "Privacy Policy": { fr: "Politique de confidentialité", pt: "Política de Privacidade", ar: "سياسة الخصوصية", sw: "Sera ya Faragha", ha: "Sufofin Tsare Sirri", es: "Política de Privacidad" },
  "Imprint": { fr: "Mentions légales", pt: "Impressão", ar: "بصمة", sw: "Imprint", ha: "Buga", es: "Impronta" },
  "Transporter Code of Conduct": { fr: "Code de conduite du transporteur", pt: "Código de Conduta do Transportador", ar: "مدونة قواعد سلوك الناقل", sw: "Kanuni za Maadili kwa Msafirishaji", ha: "Dokokin Da'a Na Mai Safara", es: "Código de Conducta del Transportista" },
  "Traveller Code of Conduct": { fr: "Code de conduite du voyageur", pt: "Código de Conduta do Viajante", ar: "مدونة قواعد سلوك المسافر", sw: "Kanuni za Maadili kwa Msafiri", ha: "Dokokin Da'a Na Mai Tafiya", es: "Código de Conducta del Viajero" },
`;

// Insert the new keys after the definition of exactPhrases = {
content = content.replace(/(const exactPhrases: Record<string, Partial<Record<Exclude<Locale, "en">, string>>> = \{)/, '$1' + insertions);
fs.writeFileSync(file, content);
console.log("Done");
